version: "3.8"

services:
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: unless-stopped

  auth:
    build:
      context: ./auth
    volumes:
      - ./auth:/usr/src/app
    ports:
      - "5000:5000"

  user:
    build:
      context: ./user
    volumes:
      - ./user:/usr/src/app
    ports:
      - "5002:5002"

  job:
    build:
      context: ./job
    volumes:
      - ./job:/usr/src/app
    ports:
      - "5003:5003"

  utils:
    build:
      context: ./utils
    volumes:
      - ./utils:/usr/src/app
    ports:
      - "5001:5001"